# This is a basic workflow to help you get started with Actions
name: Release

on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter config --enable-android
      - run: flutter build windows
      - run: flutter build apk

      - name: Zip artifact for deployment
        uses: vimtor/action-zip@v1
        with:
          files: build/windows/runner/Release/. LICENSE
          dest: windows.zip
          
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "windows.zip,build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
